# Your SonarCloud Organization and Project Keys
sonar.organization=talal2323
sonar.projectKey=talal2323

# Tell Sonar exactly which folders to scan (ignoring node_modules)
sonar.sources=backend/src,frontend/src