# Required Metadata
sonar.projectKey=notes-app-backend
sonar.projectName=Notes App Backend (10P SHINE)
sonar.projectVersion=1.0

# Path to the source code (tell Sonar where to look)
sonar.sources=src,server.js

# Exclude test files and node modules from the general scan
sonar.exclusions=node_modules/**, **/*.spec.js, **/*.test.js

# Setup rules for JavaScript
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Fail the pipeline if code quality drops below these thresholds (The "Quality Gate")
sonar.qualitygate.wait=true